# Must pass on the merge with the master branch
status = [
    "check",
]

# Small timeout for now, for faster iteration on bors testing
timeout_sec = 300

# Enable as soon as there is a CODEOWNERS file
# use_codeowners = false

# I cannot do this on my own repository, because I cannot approve my own
# PRs.

# required_approvals = 1
# up_to_date_approvals = true
