name: PR Auto Label
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: auto-label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "size:XS",
              "20": "size:S",
              "50": "size:M",
              "200": "size:L",
              "800": "size:XL",
              "2000": "size:XXL"
            }

