name: Zola on GitHub Pages

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: codeandmedia/zola_docsascode_theme
          path: docs/themes/zola_docsascode_theme
      - name: build only
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: doc
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: codeandmedia/zola_docsascode_theme
          path: docs/themes/zola_docsascode_theme
      - uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: doc
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

